languages:
  supported:
    - en
    - es
  default_lang: en
  include_default_lang: false
  include_default_lang_file_extension: false
  translations: true
home:
  alias: /home
  hide_in_urls: false
pages:
  type: regular
  dirs:
    - 'page://'
  theme: mundana
  order:
    by: default
    dir: asc
  list:
    count: 20
  dateformat:
    default: null
    short: 'jS M Y'
    long: 'jS M Y'
  publish_dates: true
cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: g
twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: true
assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true
debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
